/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelARouteImport } from './routes/hotel-a'
import { Route as HotelAIndexRouteImport } from './routes/hotel-a.index'
import { Route as HotelACartRouteImport } from './routes/hotel-a.cart'
import { Route as HotelACheckoutRouteImport } from './routes/hotel-a.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelARoute = HotelARouteImport.update({
  id: '/hotel-a',
  path: '/hotel-a',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelAIndexRoute = HotelAIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelARoute,
} as any)
const HotelACartRoute = HotelACartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => HotelARoute,
} as any)
const HotelACheckoutRoute = HotelACheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => HotelARoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hotel-a': typeof HotelARouteWithChildren
  '/hotel-a/cart': typeof HotelACartRoute
  '/hotel-a/checkout': typeof HotelACheckoutRoute
  '/hotel-a/': typeof HotelAIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hotel-a/cart': typeof HotelACartRoute
  '/hotel-a/checkout': typeof HotelACheckoutRoute
  '/hotel-a': typeof HotelAIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hotel-a': typeof HotelARouteWithChildren
  '/hotel-a/cart': typeof HotelACartRoute
  '/hotel-a/checkout': typeof HotelACheckoutRoute
  '/hotel-a/': typeof HotelAIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/hotel-a' | '/hotel-a/cart' | '/hotel-a/checkout' | '/hotel-a/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hotel-a/cart' | '/hotel-a/checkout' | '/hotel-a'
  id:
    | '__root__'
    | '/'
    | '/hotel-a'
    | '/hotel-a/cart'
    | '/hotel-a/checkout'
    | '/hotel-a/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelARoute: typeof HotelARouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-a': {
      id: '/hotel-a'
      path: '/hotel-a'
      fullPath: '/hotel-a'
      preLoaderRoute: typeof HotelARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-a/': {
      id: '/hotel-a/'
      path: '/'
      fullPath: '/hotel-a/'
      preLoaderRoute: typeof HotelAIndexRouteImport
      parentRoute: typeof HotelARoute
    }
    '/hotel-a/cart': {
      id: '/hotel-a/cart'
      path: '/cart'
      fullPath: '/hotel-a/cart'
      preLoaderRoute: typeof HotelACartRouteImport
      parentRoute: typeof HotelARoute
    }
    '/hotel-a/checkout': {
      id: '/hotel-a/checkout'
      path: '/checkout'
      fullPath: '/hotel-a/checkout'
      preLoaderRoute: typeof HotelACheckoutRouteImport
      parentRoute: typeof HotelARoute
    }
  }
}

interface HotelARouteChildren {
  HotelACartRoute: typeof HotelACartRoute
  HotelACheckoutRoute: typeof HotelACheckoutRoute
  HotelAIndexRoute: typeof HotelAIndexRoute
}

const HotelARouteChildren: HotelARouteChildren = {
  HotelACartRoute: HotelACartRoute,
  HotelACheckoutRoute: HotelACheckoutRoute,
  HotelAIndexRoute: HotelAIndexRoute,
}

const HotelARouteWithChildren =
  HotelARoute._addFileChildren(HotelARouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelARoute: HotelARouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
